name = "Mc"
author = "ana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddb988b2c6514fc4b93dbe15a844f50f07404bbe0891dbb99937b2a4dda54fb1"

[versions]
minecraft = "1.21.10"
neoforge = "21.10.64"
