name = "Mc"
author = "ana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3805c666c435831fe582c71fa0f240b389a05d52f08fcfd1ec5c60b8602a7e6"

[versions]
minecraft = "1.21.10"
neoforge = "21.10.64"
