name = "Mc"
author = "ana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66bb1ee2f73cb3abedb6905cbbf13650da6f849693b53fcdc734b4d4e652a741"

[versions]
minecraft = "1.21.10"
neoforge = "21.10.64"
